config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 15 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:error] = 'You must be logged in to perform this action.'
    redirect_to login_path
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    return unless message.save

    ActionCable.server.broadcast 'chatroom_channel', mod_message: message_render(message)
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]

  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user_authentication(user)
      session_assignment(user)
    else
      flash.now[:error] = 'There was something wrong with your login data.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out.'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    return unless logged_in?

    flash[:error] = 'You are already logged in.'
    redirect_to root_path
  end

  def user_authentication(user)
    user.authenticate(params[:session][:password])
  end

  def session_assignment(user)
    session[:user_id] = user.id
    flash[:success] = 'You have successfully logged in.'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.haml
%h4.ui.center.aligned.medium.icon.header
  %i.circular.orange.comments.icon
  Say something

%div.ui.two.column.grid
  %div.twelve.wide.column
    %div.ui.fluid.raised.card.chatbox
      %div.content{ id: "messages" }
        %div.ui.feed{ id: "message-container" }
          = render @messages

      %div.extra.content
        = form_for(@message, html: { class: 'ui reply form', role: 'form' }, url: message_path, remote: true) do |f|
          %div.field
            %div.ui.fluid.icon.input
              = f.text_field :body
              = f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe

  %div.four.wide.column
    %div.ui.fluid.raised.card.chatbox
      %div.content
        %div.ui.inverted.vertical.menu
          %a.active.item
            Home
          %a.item
            Messages
          %a.item
            Friends

app/views/layouts/_messages.html.haml
- flash.each do |msg_type, msg|
  = content_tag(:div, class: "ui #{msg_type} message transition") do
    %i.close.icon
    %div.header
      = msg

app/views/layouts/_navigation.html.haml
= link_to 'Chatroom', root_path, class: 'item'
%a.item
  Messages
%div.right.menu
  %div.ui.dropdown.item
    Account
    %i.dropdown.icon
    %div.menu
      - if logged_in?
        = link_to 'Logout', logout_path, method: :delete, class: 'item'
      - else
        = link_to 'Log in', login_path, class: 'item'
  - if !logged_in?
    %div.item
      = link_to 'Log in', login_path, class: 'ui primary button'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.haml
%div.event
  %div.content
    %div.summary
      %em
        = message.user.username + ':'
      = message.body